# Generated by Django 2.2.4 on 2019-08-28 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_auto_20190828_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='members',
            field=models.ManyToManyField(through='party.PartyRegistration', to=settings.AUTH_USER_MODEL),
        ),
    ]
