# Generated by Django 2.2.4 on 2019-08-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0004_party_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='members',
        ),
    ]
